=== saasquatch/schema/src/json/integrations/LinkInterceptorRequestBody.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Link Interceptor POST request schema",
  "description": "Sent when a shareLink is clicked and the Link Interceptor is on",
  "type": "object",
  "properties": {
    "tenantAlias": {
      "type": "string",
      "title": "Tenant Alias",
      "description": "Tenant from which the given shareLink is from"
    },
    "programId": {
      "type": "string",
      "title": "Program Id",
      "description": "The Id of the program the given shareLink is from"
    },
    "referralCode": {
      "type": "string",
      "title": "Referral Code",
      "description": "The Referrers code that will be used by the referred for the referral"
    },
    "shareLink": {
      "type": "string",
      "title": "Share Link",
      "description": "The referrer's shareLink clicked by the referred for the referral"
    },
    "referrer": {
      "type": "object",
      "description": "The Referrer user who is associated with the shareLink that was clicked on",
      "properties": {
        "id": {
          "type": "string",
          "title": "User Id",
          "description": "The user's unique identifier"
        },
        "accountId": {
          "type": "string",
          "title": "Account Id",
          "description": "The user's unique account identifier"
        },
        "firstName": {
          "type": "string",
          "title": "First Name",
          "description": "The user's first name"
        },
        "lastName": {
          "type": "string",
          "title": "First Name",
          "description": "The user's last name"
        },
        "email": {
          "type": "string",
          "title": "Email",
          "description": "The user's email address"
        },
        "imageUrl": {
          "type": "string",
          "title": "Image Url",
          "description": "The URL to an image of this user"
        }
      }
    },
    "integrationConfig": {
      "title": "Integration Configuration",
      "description": "Configuration setting for the integration",
      "type": "object"
    },
    "downstreamUrl": {
      "type": "string",
      "title": "Down Stream Link",
      "description": "The link that the user would be redirected to in absence of an integration"
    },
    "signupUrl": {
      "type": "string",
      "title": "Signup Link",
      "description": "The original signup URL configured by the program which has not been changed or processed by any integrations"
    },
    "urlParams": {
      "type": "object",
      "title": "URL Parameters",
      "description": "The URL parameters SaaSquatch backend would be attaching to the signupUrl"
    }
  }
}

=== saasquatch/schema/examples/integrations/AppsFlyerRequestBody.json
{
  "tenantAlias": "test_safdsgsfghxbcvxgfsdg",
  "programId": "referral",
  "referralCode": "LORETTABURKE",
  "shareLink": "http://example.com/free?mn",
  "referrer": {
    "id": "5d963756e4b08121fc35b384",
    "accountId": "ICMVMRLASZRULVSB",
    "firstName": "Loretta",
    "lastName": "Burke",
    "imageUrl": ""
  },
  "integrationConfig": {
    "referral": "http://saasquatch.onelink.me/btab/referraltest"
  },
  "downstreamUrl": "http://www.example.com/referrals?utm_source=invite&utm_medium=link&utm_campaign=saasquatch&rsCode=LORETTABURKE&rsShareMedium=UNKNOWN&rsEngagementMedium=UNKNOWN&_saasquatch=eyJzdGFnaW5nLnJlZmVycmFsc2Fhc3F1YXRjaC5jb20iOnsidGVzdF9hY29jYXl0NGFvdjl6X0NPREUiOnsiY29kZXMiOnsiYSI6Ik9ORUxJTksyNzMiLCJiIjoiT05FTElOSzIzNyIsImNsYXNzaWMiOiJPTkVMSU5LIiwicHJvZ3JhbWEiOiIxMUNPREU3NTQ5In0sImNvZGVzRXhwIjp7Ik9ORUxJTksyNzMiOjE2MjgyMDk2MTMsIjExQ09ERTc1NDkiOjE2MjY4MTcxNzIsIk9ORUxJTksyMzciOjE2MjgyODM3OTl9LCJsaW5rcyI6eyJhIjoiaHR0cHM6Ly9kZXJlay10ZXN0LnNzcXQuY28vbXp6eWhxIiwiYiI6Imh0dHBzOi8vZGVyZWstdGVzdC5zc3F0LmNvL216enlociJ9LCJsaW5rc0V4cCI6eyJodHRwczovL2RlcmVrLXRlc3Quc3NxdC5jby9tenp5aHIiOjE2MjgyODM3OTksImh0dHBzOi8vZGVyZWstdGVzdC5zc3F0LmNvL216enlocSI6MTYyODIwOTYxM319fX0",
  "signupUrl": "http://www.example.com/referrals?utm_source=invite&utm_medium=link&utm_campaign=saasquatch&rsCode=LORETTABURKE&rsShareMedium=UNKNOWN&rsEngagementMedium=UNKNOWN&_saasquatch=eyJzdGFnaW5nLnJlZmVycmFsc2Fhc3F1YXRjaC5jb20iOnsidGVzdF9hY29jYXl0NGFvdjl6X0NPREUiOnsiY29kZXMiOnsiYSI6Ik9ORUxJTksyNzMiLCJiIjoiT05FTElOSzIzNyIsImNsYXNzaWMiOiJPTkVMSU5LIiwicHJvZ3JhbWEiOiIxMUNPREU3NTQ5In0sImNvZGVzRXhwIjp7Ik9ORUxJTksyNzMiOjE2MjgyMDk2MTMsIjExQ09ERTc1NDkiOjE2MjY4MTcxNzIsIk9ORUxJTksyMzciOjE2MjgyODM3OTl9LCJsaW5rcyI6eyJhIjoiaHR0cHM6Ly9kZXJlay10ZXN0LnNzcXQuY28vbXp6eWhxIiwiYiI6Imh0dHBzOi8vZGVyZWstdGVzdC5zc3F0LmNvL216enlociJ9LCJsaW5rc0V4cCI6eyJodHRwczovL2RlcmVrLXRlc3Quc3NxdC5jby9tenp5aHIiOjE2MjgyODM3OTksImh0dHBzOi8vZGVyZWstdGVzdC5zc3F0LmNvL216enlocSI6MTYyODIwOTYxM319fX0"
}
