=== saasquatch/schema/src/json/user/UserInput.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "User Input",
  "description": "The input for the user upsert API",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "title": "ID",
      "description": "User ID",
      "type": "string",
      "minLength": 1
    },
    "accountId": {
      "title": "Account ID",
      "description": "Account ID",
      "type": "string",
      "minLength": 1
    },
    "firstName": {
      "title": "First Name",
      "description": "The user's first name",
      "type": "string"
    },
    "lastName": {
      "title": "Last Name",
      "description": "The user's last name",
      "type": "string"
    },
    "referralCode": {
      "title": "Referral Code",
      "description": "The user's classic referral code",
      "type": "string",
      "minLength": 1,
      "maxLength": 64
    },
    "referralCodes": {
      "title": "Referral Codes",
      "description": "The user's referral codes across programs",
      "type": "object"
    },
    "shareLinks": {
      "title": "Share Links",
      "description": "The user's share links across programs",
      "type": "object"
    },
    "imageUrl": {
      "title": "Image URL",
      "description": "The URL of the user's avatar image",
      "type": "string",
      "minLength": 1
    },
    "email": {
      "title": "Email",
      "description": "The user's email address",
      "type": "string",
      "minLength": 5
    },
    "locale": {
      "title": "Locale",
      "description": "The user's locale",
      "type": "string",
      "minLength": 2
    },
    "countryCode": {
      "title": "Country Code",
      "description": "The user's country code",
      "type": "string",
      "minLength": 2,
      "maxLength": 2
    },
    "referredBy": {
      "title": "Referred By",
      "description": "The classic referred by information",
      "additionalProperties": false,
      "properties": {
        "isConverted": {
          "title": "Is Converted (classic only)",
          "description": "Whether this referral is supposed to be converted",
          "type": "boolean"
        },
        "code": {
          "title": "Referral Code",
          "description": "The referral code that this user is referred by",
          "type": "string"
        }
      }
    },
    "referredByCodes": {
      "title": "Referred By Codes",
      "description": "The list of referral codes this user is referred by",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "cookies": {
      "title": "Cookies",
      "description": "The encoded value of referral cookies used by Squatch.js",
      "type": "string"
    },
    "referable": {
      "title": "Referable",
      "description": "Whether the account of the user can be referred",
      "type": "boolean"
    },
    "customFields": {
      "title": "Custom Fields",
      "description": "The user's custom fields",
      "type": "object"
    },
    "segments": {
      "title": "Segments",
      "description": "The segment operations to be performed on this user's segments",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dateCreated": {
      "title": "Date Created",
      "description": "The date this user was created in milliseconds since EPOCH",
      "type": "integer"
    },
    "dateUsTaxFormSubmitted": {
      "title": "Date US Tax Form Submitted",
      "description": "The date this user submitted their US tax form in milliseconds since EPOCH",
      "type": "integer"
    },
    "programGoals": {
      "title": "Program Goals",
      "description": "The override program goal values",
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "goalId",
          "programId",
          "count",
          "firstDate",
          "lastDate",
          "conversionCount"
        ],
        "properties": {
          "goalId": {
            "title": "Goal ID",
            "description": "The program goal ID",
            "type": "string"
          },
          "programId": {
            "title": "Program ID",
            "description": "The program ID this goal ID is for",
            "type": "string"
          },
          "count": {
            "title": "Count",
            "description": "The number of times this goal has been achieved",
            "type": "integer"
          },
          "firstDate": {
            "title": "First Date",
            "description": "The date this goal was achieved for the first time in milliseconds since EPOCH",
            "type": "integer"
          },
          "lastDate": {
            "title": "Last Date",
            "description": "The date this goal was achieved for the last time in milliseconds since EPOCH",
            "type": "integer"
          },
          "conversionCount": {
            "title": "Conversion Count",
            "description": "The number of conversions",
            "type": "integer"
          }
        }
      }
    }
  }
}

=== saasquatch/schema/examples/jobs/user/UserWithLinksAndCodes.json
{
  "customFields": {},
  "referralCodes": { "referrala": "Free" },
  "shareLinks": { "referrala": "http://example.com/free" },
  "referredBy": {},
  "id": "123",
  "accountId": "123",
  "firstName": "Bo",
  "lastName": "Testerson",
  "referable": true,
  "locale": "en_CA",
  "email": "bo.testerson@example.com",
  "dateCreated": 1580257434000
}
